import pandas as pd
import aemo_pi

pi = aemo_pi.connect('PIProd')

# PI Tags
PI_TAGS = {
    "CONTINGENCY_RAISE_AVAILABLE": "WA.SWIS.DISP.RESUP_AVA.SRAV",
    "CONTINGENCY_RAISE_REQUIRED": "WA.SWIS.DISP.RESUP_REQ.SPRQ",
    "CONTINGENCY_LOWER_AVAILABLE": "WA.SWIS.DISP.RESDN_AVA.LRAV",
    "CONTINGENCY_LOWER_REQUIREMENT": "WA.SWIS.DISP.RESDN_REQ.MW",
    "FAST_START_RESERVE_AVAILABLE": "WA.SWIS.DISP.FSUP_AVA.FSAV",
    "FAST_START_RESERVE_REQUIRED": "WA.SWIS.DISP.FSUP_REQ.MW",
    "REG_RAISE_REQUIREMENT": "WA.SWIS.AREA.AVAILLF.RQMW",
    "REG_RAISE_AVAILABLE": "WA.SWIS.AREA.AVAILLFUP.RLUC",
    "REG_RAISE_USED": "WA.SWIS.AREA.USEDLFUP.LFUU",
    "REG_LOWER_REQUIREMENT": "WA.SWIS.AREA.AVAILLF.RQMW",
    "REG_LOWER_AVAILABLE": "WA.SWIS.AREA.AVAILLFDN.RLDC",
    "REG_LOWER_USED": "WA.SWIS.AREA.USEDLFDN.LFDU",
    "REG_RANGE": "WA.AGC.RCAT.SWIS.EN_LFAS_RANG",
    "AGC_STATUS": "WA.AGC.OPA.SWIS.STAT",
    "ACE": "WA.AGC.OPA.SWIS.ACE",
    "LOAD_FORECAST": "WA.MARKET.ALARM.RTDE.LFMW",
    "FORECAST_ERROR": "WA.MARKET.ALARM.RTDE.LFDI",
    "SYSTEM_MW": "WA.SWIS.SUMM.GEN.GRMW",
    "IPP_TOTAL": "WA.IPP.SUMM.GEN.NTMW",
    "WIND_TOTAL": "WA.SWIS.SUMM.GEN_WIND.NTMW",
    "SOLAR": "WA.SWIS.SUMM.GEN_SOLAR.NTMW",
    "NSG_TOTAL": "WA.SWIS.SUMM.NSGEN.NTMW",
    "ESTIMATED_DPV_TOTAL": "WA.SWIS.PV.ESTNORM",
    "ENERGY_SHORTFALL_DS": "WA.MARKET.WEMDE.WEMDE.SFER",
    "REGULATION_SHORTFALL_DS": "WA.MARKET.WEMDE.WEMDE.SFRR",
    "CONTINGENCY_SHORTFALL_DS": "WA.MARKET.WEMDE.WEMDE.SFCR",
    "ROCOF_SHORTFALL_DS": "WA.MARKET.WEMDE.WEMDE.SFIR",
    "NETWORK_CONSTRAINT_DS": "WA.MARKET.WEMDE.WEMDE.NCVR",
    "LOW_IN_SERVICE_RESERVES_DS": "WA.MARKET.WEMDE.WEMDE.LISR",
    "ENERGY_SHORTFALL_PDS": "WA.MARKET.WEMDE.WEMDE.SFEF",
    "REGULATION_SHORTFALL_PDS": "WA.MARKET.WEMDE.WEMDE.SFRF",
    "CONTINGENCY_SHORTFALL_PDS": "WA.MARKET.WEMDE.WEMDE.SFCF",
    "ROCOF_SHORTFALL_PDS": "WA.MARKET.WEMDE.WEMDE.SFIF",
    "NETWORK_CONSTRAINT_PDS": "WA.MARKET.WEMDE.WEMDE.NCVF",
    "LOW_IN_SERVICE_RESERVES_PDS": "WA.MARKET.WEMDE.WEMDE.LISF",
    "NETWORK_CONSTRAINT_OVERRUN": "WA.MARKET.WEMDE.WEMDE.NCOR",
    "DS_RUN_FAILURE": "WA.MARKET.WEMDE.ALARM.DSRF",
    "PDS_RUN_FAILURE": "WA.MARKET.WEMDE.ALARM.PSRF",
    "WAS_RUN_FAILURE": "WA.MARKET.WEMDE.ALARM.WSRF",
    "ALARM_HEARTBEAT": "WA.MARKET.WEMDE.ALARM_FILELINK.ALRM",
    "DI_HEARTBEAT": "WA.MARKET.WEMDE.DI_FILELINK.ALRM",
    "WEMDE_STATE": "WA.MARKET.WEMDE.ALARM.WDST",
    "RTCA_APPLICATION_STATUS": "WA.APPS.RTCA.DESCR_STATES",
    "RTNET_SOLUTION": "WA.MARKET.RTNET.SOLUTION.SOLN",
    "RTCA_BASECASE_VOLTAGE_VIOL": "WA.RTCA.NUMBER_BASECASE_VOLTAGE_VIOL",
    "RTCA_BRANCH_VIOL": "WA.RTCA.NUMBER_BRANCH_VIOL",
    "RTCA_UNSOLVED": "WA.RTCA.NUMBER_UNSOLVED",
    "RTCA_VOLTAGE_VIOL": "WA.RTCA.NUMBER_VOLTAGE_VIOL",
    "BMO_FILE": "WA.MARKET.ALARM.RTDE.RBMO",
    "RTDE_MODE": "WA.MARKET.ALARM.RTDE.RTUN",
    "MARKET_LINK": "WA.MARKET.MABC.MARKET_LINK.ALRM",
    "WEM_ICCP_LINK": "AF_CALC.WA.ICCP.WEM.STATE",
    "NT_FAULT_LEVEL": "WA.NT.SPS.FAULT_LEVEL.FLA",
    "MLA_FAULT_LEVEL": "WA.MLA.SPS.FAULT_LEVEL.FLA",
    "BSI_1": "WA.BSI.CB.CB_201.CB",
    "BSI_2": "WA.BSI.CB.CB_301.CB",
    "BSI_3": "WA.BSI.CB.CB_401.CB",
    "WA_SWIS_BUS_WP_FREQ": "WA.SWIS.BUS.WP_FREQ.HZ"
}

# Categories for alarms
ALARM_CATEGORIES = {
    "Ancillary Services Alarms": [
       "CONTINGENCY RAISE AVAILABLE", "CONTINGENCY RAISE REQUIRED", "CONTINGENCY LOWER AVAILABLE",
       "CONTINGENCY LOWER REQUIREMENT", "FAST START RESERVE AVAILABLE", "FAST START RESERVE REQUIRED",
       "REG RAISE REQUIREMENT", "REG RAISE AVAILABLE", "REG RAISE USED", "REG LOWER REQUIREMENT",
       "REG LOWER AVAILABLE", "REG LOWER USED", "REG RANGE"
   ],
   "WEMDE Alarms": [
       "ENERGY SHORTFALL DS", "REGULATION SHORTFALL DS", "CONTINGENCY SHORTFALL DS", "ROCOF SHORTFALL DS",
       "NETWORK CONSTRAINT DS", "LOW IN SERVICE RESERVES DS", "ENERGY SHORTFALL PDS", "REGULATION SHORTFALL PDS",
       "CONTINGENCY SHORTFALL PDS", "ROCOF SHORTFALL PDS", "NETWORK CONSTRAINT PDS", "LOW IN SERVICE RESERVES PDS",
       "NETWORK CONSTRAINT OVERRUN", "DS RUN FAILURE", "PDS RUN FAILURE", "WAS RUN FAILURE", "WEMDE STATE"
   ],
   "Generation Overview Alarms": [
       "AGC STATUS", "ACE", "LOAD FORECAST", "FORECAST ERROR", "SYSTEM MW", "IPP TOTAL", "WIND TOTAL", "SOLAR",
       "NSG TOTAL", "ESTIMATED DPV TOTAL", "ALARM HEARTBEAT", "DI HEARTBEAT", "WA SWIS BUS WP FREQ"
   ],
   "Security Alarms": [
       "RTCA APPLICATION STATUS", "RTNET SOLUTION", "RTCA BASECASE VOLTAGE VIOL", "RTCA BRANCH VIOL",
       "RTCA UNSOLVED", "RTCA VOLTAGE VIOL", "NT FAULT LEVEL", "MLA FAULT LEVEL", "BSI 1", "BSI 2", "BSI 3"
   ],
   "Other Alarms": [
       "BMO FILE", "RTDE MODE", "MARKET LINK", "WEM ICCP LINK"
    ]
}

def get_current_values(tag_list):
    global df_alarms
    df = pi.get_current_value(tag_list)
    # Create a mapping from the PI tag values to their descriptive names, replacing underscores with spaces
    tag_mapping = {v: k.replace('_', ' ') for k, v in PI_TAGS.items()}
    # Create a DataFrame for alarms with descriptive PI tag names and their values
    df_alarms = pd.DataFrame({
        "PI Tag Name": [tag_mapping[col] for col in df.columns],
        "Value": df.iloc[0].values
    })
    # Add the category column
    df_alarms['Category'] = df_alarms['PI Tag Name'].apply(lambda x: next((k for k, v in ALARM_CATEGORIES.items() if x in v), 'Other Alarms'))
    return df, df_alarms

# Utility function to fetch and process current values
def main_function():
    tag_list = list(PI_TAGS.values())
    df, df_alarms = get_current_values(tag_list)
    return df_alarms

# Call this function as needed
main_function()

