# PI Tags

CONTINGENCY_RAISE = "WA.AGC.OPA.SWIS.RVACT3"
CONTINGENCY_RAISE_REQUIRED = "WA.SWIS.DISP.RESUP_REQ.SPRQ"
CONTINGENCY_LOWER_AVAILABLE = "WA.AGC.OPA.SWIS.RVACT7"
CONTINGENCY_LOWER_REQUIREMENT = "WA.SWIS.DISP.RESDN_REQ.MW"
FAST_START_RESERVE ="WA.AGC.OPA.SWIS.RVACT4"
FAST_START_RESERVE_REQUIRED = "WA.SWIS.DISP.FSUP_REQ.MW"
REG_RAISE_REQUIREMENT = "WA.SWIS.AREA.AVAILLF.RQMW"
REG_RAISE_AVAILABLE ="WA.SWIS.AREA.AVAILLFUP.RLUC"
REG_RAISE_USED = "WA.SWIS.AREA.USEDLFUP.LFUU"
REG_LOWER_REQUIREMENT = "WA.SWIS.AREA.AVAILLF.RQMW"
REG_LOWER_AVAILABLE = "WA.SWIS.AREA.AVAILLFDN.RLDC"
REG_LOWER_USED = "WA.SWIS.AREA.USEDLFDN.LFDU"
REG_RANGE = "WA.AGC.RCAT.SWIS.EN_LFAS_RANG"
AGC_STATUS ="WA.AGC.OPA.SWIS.STAT"
ACE = "WA.AGC.OPA.SWIS.ACE"
LOAD_FORECAST = "WA.MARKET.ALARM.RTDE.LFMW"
FORECAST_ERROR = "WA.MARKET.ALARM.RTDE.LFDI"
SYSTEM_MW ="WA.SWIS.SUMM.GEN.GRMW"
IPP_TOTAL = "WA.IPP.SUMM.GEN.NTMW"
WIND_TOTAL = "WA.SWIS.SUMM.GEN_WIND.NTMW"
SOLAR = "WA.SWIS.SUMM.GEN_SOLAR.NTMW"
NSG_TOTAL = "WA.SWIS.SUMM.NSGEN.NTMW"
ESTIMATED_DPV_TOTAL = 'WA.SWIS.PV.ESTNORM'
ENERGY_SHORTFALL_DS = "WA.MARKET.WEMDE.WEMDE.SFER"
REGULATION_SHORTFALL_DS = "WA.MARKET.WEMDE.WEMDE.SFRR"
CONTINGENCY_SHORTFALL_DS = "WA.MARKET.WEMDE.WEMDE.SFCR"
ROCOF_SHORTFALL_DS = "WA.MARKET.WEMDE.WEMDE.SFIR"
NETWORK_CONSTRAINT_DS = "WA.MARKET.WEMDE.WEMDE.NCVR"
LOW_IN_SERVICE_RESERVES_DS = "WA.MARKET.WEMDE.WEMDE.LISR"
ENERGY_SHORTFALL_PDS = "WA.MARKET.WEMDE.WEMDE.SFEF"
REGULATION_SHORTFALL_PDS = "WA.MARKET.WEMDE.WEMDE.SFRF"
CONTINGENCY_SHORTFALL_PDS = "WA.MARKET.WEMDE.WEMDE.SFCF"
ROCOF_SHORTFALL_PDS = "WA.MARKET.WEMDE.WEMDE.SFIF"
NETWORK_CONSTRAINT_PDS = "WA.MARKET.WEMDE.WEMDE.NCVF"
LOW_IN_SERVICE_RESERVES_PDS = "WA.MARKET.WEMDE.WEMDE.LISF"
NETWORK_CONSTRAINT_OVERRUN = "WA.MARKET.WEMDE.WEMDE.NCOR"
DS_RUN_FAILURE = "WA.MARKET.WEMDE.ALARM.DSRF"
PDS_RUN_FAILURE = "WA.MARKET.WEMDE.ALARM.PSRF"
WAS_RUN_FAILURE = "WA.MARKET.WEMDE.ALARM.WSRF"
ALARM_HEARTBEAT = "WA.MARKET.WEMDE.ALARM_FILELINK.ALRM"
DI_HEARTBEAT = "WA.MARKET.WEMDE.DI_FILELINK.ALRM"
WEMDE_STATE = "WA.MARKET.WEMDE.ALARM.WDST"
RTCA_APPLICATION_STATUS = "WA.APPS.RTCA.DESCR_STATES"
RTNET_SOLUTION = "WA.MARKET.RTNET.SOLUTION.SOLN"
RTCA_BASECASE_VOLTAGE_VIOL = "WA.RTCA.NUMBER_BASECASE_VOLTAGE_VIOL"
RTCA_BRANCH_VIOL = "WA.RTCA.NUMBER_BRANCH_VIOL"
RTCA_UNSOLVED = "WA.RTCA.NUMBER_UNSOLVED"
RTCA_VOLTAGE_VIOL = "WA.RTCA.NUMBER_VOLTAGE_VIOL"
BMO_FILE = "WA.MARKET.ALARM.RTDE.RBMO"
RTDE_MODE = "WA.MARKET.ALARM.RTDE.RTUN"
MARKET_LINK = "WA.MARKET.MABC.MARKET_LINK.ALRM"
WEM_ICCP_LINK = "AF_CALC.WA.ICCP.WEM.STATE"
NT_FAULT_LEVEL = "WA.NT.SPS.FAULT_LEVEL.FLA"
MLA_FAULT_LEVEL = "WA.MLA.SPS.FAULT_LEVEL.FLA"
BSI_1 = "WA.BSI.CB.CB_201.CB"
BSI_2 = "WA.BSI.CB.CB_301.CB"
BSI_3 = "WA.BSI.CB.CB_401.CB"
WA_SWIS_BUS_WP_FREQ = "WA.SWIS.BUS.WP_FREQ.HZ"

tag_list = [
    CONTINGENCY_RAISE,
    CONTINGENCY_RAISE_REQUIRED,
    CONTINGENCY_LOWER_AVAILABLE,
    CONTINGENCY_LOWER_REQUIREMENT,
    FAST_START_RESERVE,
    FAST_START_RESERVE_REQUIRED,
    REG_RAISE_REQUIREMENT,
    REG_RAISE_AVAILABLE,
    REG_RAISE_USED,
    REG_LOWER_REQUIREMENT,
    REG_LOWER_AVAILABLE,
    REG_LOWER_USED,
    REG_RANGE,
    AGC_STATUS,
    ACE,
    LOAD_FORECAST,
    FORECAST_ERROR,
    SYSTEM_MW,
    IPP_TOTAL,
    WIND_TOTAL,
    SOLAR,
    NSG_TOTAL,
    ESTIMATED_DPV_TOTAL,
    ENERGY_SHORTFALL_DS,
    REGULATION_SHORTFALL_DS,
    CONTINGENCY_SHORTFALL_DS,
    ROCOF_SHORTFALL_DS,
    NETWORK_CONSTRAINT_DS,
    LOW_IN_SERVICE_RESERVES_DS,
    ENERGY_SHORTFALL_PDS,
    REGULATION_SHORTFALL_PDS,
    CONTINGENCY_SHORTFALL_PDS,
    ROCOF_SHORTFALL_PDS,
    NETWORK_CONSTRAINT_PDS,
    LOW_IN_SERVICE_RESERVES_PDS,
    NETWORK_CONSTRAINT_OVERRUN,
    DS_RUN_FAILURE,
    PDS_RUN_FAILURE,
    WAS_RUN_FAILURE,
    ALARM_HEARTBEAT,
    DI_HEARTBEAT,
    WEMDE_STATE,
    RTCA_APPLICATION_STATUS,
    RTNET_SOLUTION,
    RTCA_BASECASE_VOLTAGE_VIOL,
    RTCA_BRANCH_VIOL,
    RTCA_UNSOLVED,
    RTCA_VOLTAGE_VIOL,
    BMO_FILE,
    RTDE_MODE,
    MARKET_LINK,
    WEM_ICCP_LINK,
    NT_FAULT_LEVEL,
    MLA_FAULT_LEVEL,
    BSI_1,
    BSI_2,
    BSI_3,
    WA_SWIS_BUS_WP_FREQ
]