# Tag dictionary with facility codes
tag_dict = {
    "ALBANY_WF1": {
        "facilitycode": "ALBANY_WF1",
        "nettmw": "WA.ALB.GEN.ALBWF.NTMW",
        "dispatchtarget": "WA.ALB.DISP.ALBWF.RBPM",
        "ramprate": "WA.ALB.DISP.ALBWF.RDRR",
        "description": "Albany Wind Farm",
        "RLM1": "WA.ALB.DISP.ALBWF.RLM1",
        "RLM2": "WA.ALB.DISP.ALBWF.RLM2",
        "RLM3": "WA.ALB.DISP.ALBWF.RLM3",
        "Reg L": "WA.ALB.DISP.ALBWF.RLDC",
        "Reg R": "WA.ALB.DISP.ALBWF.RLUC",
        "Cont L": "WA.ALB.DISP.ALBWF.RCLC",
        "Cont R": "WA.ALB.DISP.ALBWF.RCRC"
    },
    "ALCOA_WGP": {
        "facilitycode": "ALCOA_WGP",
        "nettmw": "WA.WGP.GEN.AWGP.NTMW",
        "dispatchtarget": "WA.WGP.DISP.AWGP.RBPM",
        "ramprate": "WA.WGP.DISP.AWGP.RDRR",
        "description": "Alcoa Wagerup Power",
        "RLM1": "WA.WGP.DISP.AWGP.RLM1",
        "RLM2": "WA.WGP.DISP.AWGP.RLM2",
        "RLM3": "WA.WGP.DISP.AWGP.RLM3",
        "Reg L": "WA.WGP.DISP.AWGP.RLDC",
        "Reg R": "WA.WGP.DISP.AWGP.RLUC",
        "Cont L": "WA.WGP.DISP.AWGP.RCLC",
        "Cont R": "WA.WGP.DISP.AWGP.RCRC"
    },
    "ALINTA_PNJ_U1": {
        "facilitycode": "ALINTA_PNJ_U1",
        "nettmw": "WA.APJ.GEN.GT1.NTMW",
        "dispatchtarget": "WA.APJ.DISP.GT1.RBPM",
        "ramprate": "WA.APJ.DISP.GT1.RDRR",
        "description": "Alinta Pinjarra Unit 1",
        "RLM1": "WA.APJ.DISP.GT1.RLM1",
        "RLM2": "WA.APJ.DISP.GT1.RLM2",
        #"RLM3": "WA.APJ.DISP.GT1.RLM3",
        "Reg L": "WA.APJ.DISP.GT1.RLDC",
        "Reg R": "WA.APJ.DISP.GT1.RLUC",
        "Cont L": "WA.APJ.DISP.GT1.RCLC",
        "Cont R": "WA.APJ.DISP.GT1.RCRC"
    },
    "ALINTA_PNJ_U2": {
        "facilitycode": "ALINTA_PNJ_U2",
        "nettmw": "WA.APJ9.GEN.GT2.NTMW",
        "dispatchtarget": "WA.APJ9.DISP.GT2.RBPM",
        "ramprate": "WA.APJ9.DISP.GT2.RDRR",
        "description": "Alinta Pinjarra Unit 2",
        "RLM1": "WA.APJ9.DISP.GT2.RLM1",
        "RLM2": "WA.APJ9.DISP.GT2.RLM2",
        #"RLM3": "WA.APJ9.DISP.GT2.RLM3",
        "Reg L": "WA.APJ9.DISP.GT2.RLDC",
        "Reg R": "WA.APJ9.DISP.GT2.RLUC",
        "Cont L": "WA.APJ9.DISP.GT2.RCLC",
        "Cont R": "WA.APJ9.DISP.GT2.RCRC"
    },
    "ALINTA_WGP_GT": {
        "facilitycode": "ALINTA_WGP_GT",
        "nettmw": "WA.WGP9.GEN.GT1.NTMW",
        "dispatchtarget": "WA.WGP9.DISP.GT1.RBPM",
        "ramprate": "WA.WGP9.DISP.GT1.RDRR",
        "description": "Alinta Wagerup GT",
        "RLM1": "WA.WGP9.DISP.GT1.RLM1",
        "RLM2": "WA.WGP9.DISP.GT1.RLM2",
        #"RLM3": "WA.WGP9.DISP.GT1.RLM3",
        "Reg L": "WA.WGP9.DISP.GT1.RLDC",
        "Reg R": "WA.WGP9.DISP.GT1.RLUC",
        "Cont L": "WA.WGP9.DISP.GT1.RCLC",
        "Cont R": "WA.WGP9.DISP.GT1.RCRC"
    },
    "ALINTA_WGP_U2": {
        "facilitycode": "ALINTA_WGP_U2",
        "nettmw": "WA.WGP9.GEN.GT2.NTMW",
        "dispatchtarget": "WA.WGP9.DISP.GT2.RBPM",
        "ramprate": "WA.WGP9.DISP.GT2.RDRR",
        "description": "Alinta Wagerup U2",
        "RLM1": "WA.WGP9.DISP.GT2.RLM1",
        "RLM2": "WA.WGP9.DISP.GT2.RLM2",
        #"RLM3": "WA.WGP9.DISP.GT2.RLM3",
        "Reg L": "WA.WGP9.DISP.GT2.RLDC",
        "Reg R": "WA.WGP9.DISP.GT2.RLUC",
        "Cont L": "WA.WGP9.DISP.GT2.RCLC",
        "Cont R": "WA.WGP9.DISP.GT2.RCRC"
    },
    "ALINTA_WWF": {
        "facilitycode": "ALINTA_WWF",
        "nettmw": "WA.WWF.GEN.WWF.NTMW",
        "dispatchtarget": "WA.WWF.DISP.WWF.RBPM",
        "ramprate": "WA.WWF.DISP.WWF.RDRR",
        "description": "Walkaway Wind Farm",
        "RLM1": "WA.WWF.DISP.WWF.RLM1",
        "RLM2": "WA.WWF.DISP.WWF.RLM2",
        "RLM3": "WA.WWF.DISP.WWF.RLM3",
        "Reg L": "WA.WWF.DISP.WWF.RLDC",
        "Reg R": "WA.WWF.DISP.WWF.RLUC",
        "Cont L": "WA.WWF.DISP.WWF.RCLC",
        "Cont R": "WA.WWF.DISP.WWF.RCRC"
    },
    "BADGINGARRA_WF1": {
        "facilitycode": "BADGINGARRA_WF1",
        "nettmw": "WA.BWF.GEN.BWF.NTMW",
        "dispatchtarget": "WA.BWF.DISP.BWF.RBPM",
        "ramprate": "WA.BWF.DISP.BWF.RDRR",
        "description": "Badgingarra Wind Farm",
        "RLM1": "WA.BWF.DISP.BWF.RLM1",
        "RLM2": "WA.BWF.DISP.BWF.RLM2",
        "RLM3": "WA.BWF.DISP.BWF.RLM3",
        "Reg L": "WA.BWF.DISP.BWF.RLDC",
        "Reg R": "WA.BWF.DISP.BWF.RLUC",
        "Cont L": "WA.BWF.DISP.BWF.RCLC",
        "Cont R": "WA.BWF.DISP.BWF.RCRC"
    },
    "BW1_BLUEWATERS_G2": {
        "facilitycode": "BW1_BLUEWATERS_G2",
        "nettmw": "WA.BWP.GEN.G1.NTMW",
        "dispatchtarget": "WA.BWP.DISP.G1.RBPM",
        "ramprate": "WA.BWP.DISP.G1.RDRR",
        "description": "Bluewaters Power Station G2",
        #"RLM1": "WA.BWP.DISP.G1.RLM1",
        "RLM2": "WA.BWP.DISP.G1.RLM2",
        "RLM3": "WA.BWP.DISP.G1.RLM3",
        "Reg L": "WA.BWP.DISP.G1.RLDC",
        "Reg R": "WA.BWP.DISP.G1.RLUC",
        "Cont L": "WA.BWP.DISP.G1.RCLC",
        "Cont R": "WA.BWP.DISP.G1.RCRC"
    },
    "BW2_BLUEWATERS_G1": {
        "facilitycode": "BW2_BLUEWATERS_G1",
        "nettmw": "WA.BWP.GEN.G2.NTMW",
        "dispatchtarget": "WA.BWP.DISP.G2.RBPM",
        "ramprate": "WA.BWP.DISP.G2.RDRR",
        "description": "Bluewaters Power Station G1",
        #"RLM1": "WA.BWP.DISP.G2.RLM1",
        "RLM2": "WA.BWP.DISP.G2.RLM2",
        "RLM3": "WA.BWP.DISP.G2.RLM3",
        "Reg L": "WA.BWP.DISP.G2.RLDC",
        "Reg R": "WA.BWP.DISP.G2.RLUC",
        "Cont L": "WA.BWP.DISP.G2.RCLC",
        "Cont R": "WA.BWP.DISP.G2.RCRC"
    },
    "COCKBURN_CCG1": {
        "facilitycode": "COCKBURN_CCG1",
        "nettmw": "WA.CKB.GEN.CKB.NTMW",
        "dispatchtarget": "WA.CKB.DISP.CKB.RBPM",
        "ramprate": "WA.CKB.DISP.CKB.RDRR",
        "description": "Cockburn Combined Cycle",
        "RLM1": "WA.CKB.DISP.CKB.RLM1",
        "RLM2": "WA.CKB.DISP.CKB.RLM2",
        "RLM3": "WA.CKB.DISP.CKB.RLM3",
        "Reg L": "WA.CKB.DISP.CKB.RLDC",
        "Reg R": "WA.CKB.DISP.CKB.RLUC",
        "Cont L": "WA.CKB.DISP.CKB.RCLC",
        "Cont R": "WA.CKB.DISP.CKB.RCRC"
    },
    "COLLIE_G1": {
        "facilitycode": "COLLIE_G1",
        "nettmw": "WA.CPS.GEN.G1.NTMW",
        "dispatchtarget": "WA.CPS.DISP.G1.RBPM",
        "ramprate": "WA.CPS.DISP.G1.RDRR",
        "description": "Collie Power Station G1",
        "RLM1": "WA.CPS.DISP.G1.RLM1",
        "RLM2": "WA.CPS.DISP.G1.RLM2",
        "RLM3": "WA.CPS.DISP.G1.RLM3",
        "Reg L": "WA.CPS.DISP.G1.RLDC",
        "Reg R": "WA.CPS.DISP.G1.RLUC",
        "Cont L": "WA.CPS.DISP.G1.RCLC",
        "Cont R": "WA.CPS.DISP.G1.RCRC"
    },
       "EDWFMAN_WF1": {
        "facilitycode": "EDWFMAN_WF1",
        "nettmw": "WA.EMD.GEN.EMD.NTMW",
        "dispatchtarget": "WA.EMD.DISP.EMD.RBPM",
        "ramprate": "WA.EMD.DISP.EMD.RDRR",
        "description": "Emu Downs Wind Farm",
        "RLM1": "WA.EMD.DISP.EMD.RLM1",
        "RLM2": "WA.EMD.DISP.EMD.RLM2",
        "RLM3": "WA.EMD.DISP.EMD.RLM3",
        "Reg L": "WA.EMD.DISP.EMD.RLDC",
        "Reg R": "WA.EMD.DISP.EMD.RLUC",
        "Cont L": "WA.EMD.DISP.EMD.RCLC",
        "Cont R": "WA.EMD.DISP.EMD.RCRC"
   
    },
       "FLATROCKS_WF1": {
        "facilitycode": "FLATROCKS_WF1",
        "nettmw": "WA.FRW.GEN.FRW.NTMW",
        "dispatchtarget": "WA.FRW.DISP.FRW.RBPM",
        "ramprate": "WA.FRW.DISP.FRW.RDRR",
        "description": "Flat Rocks Wind Farm",
        "RLM1": "WA.FRW.DISP.FRW.RLM1",
        "RLM2": "WA.FRW.DISP.FRW.RLM2",
        "RLM3": "WA.FRW.DISP.FRW.RLM3",
        "Reg L": "WA.FRW.DISP.FRW.RLDC",
        "Reg R": "WA.FRW.DISP.FRW.RLUC",
        "Cont L": "WA.FRW.DISP.FRW.RCLC",
        "Cont R": "WA.FRW.DISP.FRW.RCRC"
      },    
    "GRASMERE_WF1": {
        "facilitycode": "GRASMERE_WF1",
        "nettmw": "WA.ALB.GEN.GWF.NTMW",
        "dispatchtarget": "WA.ALB.DISP.ALBGWF.RBPM",
        "ramprate": "WA.ALB.DISP.ALBGWF.RDRR",
        "description": "Grasmere Wind Farm",
        "RLM1": "WA.ALB.DISP.ALBGWF.RLM1",
        "RLM2": "WA.ALB.DISP.ALBGWF.RLM2",
        "RLM3": "WA.ALB.DISP.ALBGWF.RLM3",
        "Reg L": "WA.ALB.DISP.ALBGWF.RLDC",
        "Reg R": "WA.ALB.DISP.ALBGWF.RLUC",
        "Cont L": "WA.ALB.DISP.ALBGWF.RCLC",
        "Cont R": "WA.ALB.DISP.ALBGWF.RCRC"
    },
    "GREENOUGH_RIVER_PV1": {
        "facilitycode": "GREENOUGH_RIVER_PV1",
        "nettmw": "WA.MGS.GEN.MGS.NTMW",
        "dispatchtarget": "WA.MGS.DISP.MGS.RBPM",
        "ramprate": "WA.MGS.DISP.MGS.RDRR",
        "description": "Greenough River Solar Farm",
        "RLM1": "WA.MGS.DISP.MGS.RLM1",
        "RLM2": "WA.MGS.DISP.MGS.RLM2",
        "RLM3": "WA.MGS.DISP.MGS.RLM3",
        "Reg L": "WA.MGS.DISP.MGS.RLDC",
        "Reg R": "WA.MGS.DISP.MGS.RLUC",
        "Cont L": "WA.MGS.DISP.MGS.RCLC",
        "Cont R": "WA.MGS.DISP.MGS.RCRC"
    },
    "INVESTEC_COLLGAR_WF1": {
        "facilitycode": "INVESTEC_COLLGAR_WF1",
        "nettmw": "WA.CGW.GEN.CGW.NTMW",
        "dispatchtarget": "WA.CGW.DISP.CGW.RBPM",
        "ramprate": "WA.CGW.DISP.CGW.RDRR",
        "description": "Collgar Wind Farm",
        "RLM1": "WA.CGW.DISP.CGW.RLM1",
        "RLM2": "WA.CGW.DISP.CGW.RLM2",
        "RLM3": "WA.CGW.DISP.CGW.RLM3",
        "Reg L": "WA.CGW.DISP.CGW.RLDC",
        "Reg R": "WA.CGW.DISP.CGW.RLUC",
        "Cont L": "WA.CGW.DISP.CGW.RCLC",
        "Cont R": "WA.CGW.DISP.CGW.RCRC"
    },
    "KEMERTON_GT11": {
        "facilitycode": "KEMERTON_GT11",
        "nettmw": "WA.KMP.GEN.GT11.NTMW",
        "dispatchtarget": "WA.KMP.DISP.GT11.RBPM",
        "ramprate": "WA.KMP.DISP.GT11.RDRR",
        "description": "Kemerton Power Station GT11",
        "RLM1": "WA.KMP.DISP.GT11.RLM1",
        "RLM2": "WA.KMP.DISP.GT11.RLM2",
        "RLM3": "WA.KMP.DISP.GT11.RLM3",
        "Reg L": "WA.KMP.DISP.GT11.RLDC",
        "Reg R": "WA.KMP.DISP.GT11.RLUC",
        "Cont L": "WA.KMP.DISP.GT11.RCLC",
        "Cont R": "WA.KMP.DISP.GT11.RCRC"
    },
    "KEMERTON_GT12": {
        "facilitycode": "KEMERTON_GT12",
        "nettmw": "WA.KMP.GEN.GT12.NTMW",
        "dispatchtarget": "WA.KMP.DISP.GT12.RBPM",
        "ramprate": "WA.KMP.DISP.GT12.RDRR",
        "description": "Kemerton Power Station GT12",
        "RLM1": "WA.KMP.DISP.GT12.RLM1",
        "RLM2": "WA.KMP.DISP.GT12.RLM2",
        "RLM3": "WA.KMP.DISP.GT12.RLM3",
        "Reg L": "WA.KMP.DISP.GT12.RLDC",
        "Reg R": "WA.KMP.DISP.GT12.RLUC",
        "Cont L": "WA.KMP.DISP.GT12.RCLC",
        "Cont R": "WA.KMP.DISP.GT12.RCRC"
    },
    "KWINANA_ESR1": {
        "facilitycode": "KWINANA_ESR1",
        "nettmw": "WA.KWB.GEN.KWB1.NTMW",
        "dispatchtarget": "WA.KWB.DISP.KWB1.RBPM",
        "ramprate": "WA.KWB.DISP.KWB1.RDRR",
        "description": "Kwinana Power Station ESR1",
        "RLM1": "WA.KWB.DISP.KWB1.RLM1",
        "RLM2": "WA.KWB.DISP.KWB1.RLM2",
        "RLM3": "WA.KWB.DISP.KWB1.RLM3",
        "Reg L": "WA.KWB.DISP.KWB1.RLDC",
        "Reg R": "WA.KWB.DISP.KWB1.RLUC",
        "Cont L": "WA.KWB.DISP.KWB1.RCLC",
        "Cont R": "WA.KWB.DISP.KWB1.RCRC"
    },
        "KWINANA_ESR2": {
        "facilitycode": "KWINANA_ESR2",
        "nettmw": "WA.KWB.GEN.KWB2.NTMW",
        "dispatchtarget": "WA.KWB.DISP.KWB2.RBPM",
        "ramprate": "WA.KWB.DISP.KWB2.RDRR",
        "description": "Kwinana Power Station ESR2",
        "RLM1": "WA.KWB.DISP.KWB2.RLM1",
        "RLM2": "WA.KWB.DISP.KWB2.RLM2",
        "RLM3": "WA.KWB.DISP.KWB2.RLM3",
        "Reg L": "WA.KWB.DISP.KWB2.RLDC",
        "Reg R": "WA.KWB.DISP.KWB2.RLUC",
        "Cont L": "WA.KWB.DISP.KWB2.RCLC",
        "Cont R": "WA.KWB.DISP.KWB2.RCRC"
    },
    "KWINANA_GT2": {
        "facilitycode": "KWINANA_GT2",
        "nettmw": "WA.KPS.GEN.GT2.NTMW",
        "dispatchtarget": "WA.KPS.DISP.GT2.RBPM",
        "ramprate": "WA.KPS.DISP.GT2.RDRR",
        "description": "Kwinana Power Station GT2",
        "RLM1": "WA.KPS.DISP.GT2.RLM1",
        "RLM2": "WA.KPS.DISP.GT2.RLM2",
        "RLM3": "WA.KPS.DISP.GT2.RLM3",
        "Reg L": "WA.KPS.DISP.GT2.RLDC",
        "Reg R": "WA.KPS.DISP.GT2.RLUC",
        "Cont L": "WA.KPS.DISP.GT2.RCLC",
        "Cont R": "WA.KPS.DISP.GT2.RCRC"
    },
    "KWINANA_GT3": {
        "facilitycode": "KWINANA_GT3",
        "nettmw": "WA.KPS.GEN.GT3.NTMW",
        "dispatchtarget": "WA.KPS.DISP.GT3.RBPM",
        "ramprate": "WA.KPS.DISP.GT3.RDRR",
        "description": "Kwinana Power Station GT3",
        "RLM1": "WA.KPS.DISP.GT3.RLM1",
        "RLM2": "WA.KPS.DISP.GT3.RLM2",
        "RLM3": "WA.KPS.DISP.GT3.RLM3",
        "Reg L": "WA.KPS.DISP.GT3.RLDC",
        "Reg R": "WA.KPS.DISP.GT3.RLUC",
        "Cont L": "WA.KPS.DISP.GT3.RCLC",
        "Cont R": "WA.KPS.DISP.GT3.RCRC"
    },
    "MERSOLAR_PV1": {
        "facilitycode": "MERSOLAR_PV1",
        "nettmw": "WA.MRS.GEN.MRS.NTMW",
        "dispatchtarget": "WA.MRS.DISP.MRS.RBPM",
        "ramprate": "WA.MRS.DISP.MRS.RDRR",
        "description": "Merredin Solar Farm",
        "RLM1": "WA.MRS.DISP.MRS.RLM1",
        "RLM2": "WA.MRS.DISP.MRS.RLM2",
        "RLM3": "WA.MRS.DISP.MRS.RLM3",
        "Reg L": "WA.MRS.DISP.MRS.RLDC",
        "Reg R": "WA.MRS.DISP.MRS.RLUC",
        "Cont L": "WA.MRS.DISP.MRS.RCLC",
        "Cont R": "WA.MRS.DISP.MRS.RCRC"
    },
    "MUJA_G6": {
        "facilitycode": "MUJA_G6",
        "nettmw": "WA.MU.GEN.G6.NTMW",
        "dispatchtarget": "WA.MU.DISP.G6.RBPM",
        "ramprate": "WA.MU.DISP.G6.RDRR",
        "description": "Muja Power Station G6",
        "RLM1": "WA.MU.DISP.G6.RLM1",
        "RLM2": "WA.MU.DISP.G6.RLM2",
        "RLM3": "WA.MU.DISP.G6.RLM3",
        "Reg L": "WA.MU.DISP.G6.RLDC",
        "Reg R": "WA.MU.DISP.G6.RLUC",
        "Cont L": "WA.MU.DISP.G6.RCLC",
        "Cont R": "WA.MU.DISP.G6.RCRC"
    },
    "MUJA_G7": {
        "facilitycode": "MUJA_G7",
        "nettmw": "WA.MU.GEN.G7.NTMW",
        "dispatchtarget": "WA.MU.DISP.G7.RBPM",
        "ramprate": "WA.MU.DISP.G7.RDRR",
        "description": "Muja Power Station G7",
        "RLM1": "WA.MU.DISP.G7.RLM1",
        "RLM2": "WA.MU.DISP.G7.RLM2",
        "RLM3": "WA.MU.DISP.G7.RLM3",
        "Reg L": "WA.MU.DISP.G7.RLDC",
        "Reg R": "WA.MU.DISP.G7.RLUC",
        "Cont L": "WA.MU.DISP.G7.RCLC",
        "Cont R": "WA.MU.DISP.G7.RCRC"
    },
    "MUJA_G8": {
        "facilitycode": "MUJA_G8",
        "nettmw": "WA.MU.GEN.G8.NTMW",
        "dispatchtarget": "WA.MU.DISP.G8.RBPM",
        "ramprate": "WA.MU.DISP.G8.RDRR",
        "description": "Muja Power Station G8",
        "RLM1": "WA.MU.DISP.G8.RLM1",
        "RLM2": "WA.MU.DISP.G8.RLM2",
        "RLM3": "WA.MU.DISP.G8.RLM3",
        "Reg L": "WA.MU.DISP.G8.RLDC",
        "Reg R": "WA.MU.DISP.G8.RLUC",
        "Cont L": "WA.MU.DISP.G8.RCLC",
        "Cont R": "WA.MU.DISP.G8.RCRC"
    },
    "MUNGARRA_GT1": {
        "facilitycode": "MUNGARRA_GT1",
        "nettmw": "WA.MGA.GEN.GT1.NTMW",
        "dispatchtarget": "WA.MGA.DISP.GT1.RBPM",
        "ramprate": "WA.MGA.DISP.GT1.RDRR",
        "description": "Mungarra Power Station GT1",
        "RLM1": "WA.MGA.DISP.GT1.RLM1",
        "RLM2": "WA.MGA.DISP.GT1.RLM2",
        "RLM3": "WA.MGA.DISP.GT1.RLM3",
        "Reg L": "WA.MGA.DISP.GT1.RLDC",
        "Reg R": "WA.MGA.DISP.GT1.RLUC",
        "Cont L": "WA.MGA.DISP.GT1.RCLC",
        "Cont R": "WA.MGA.DISP.GT1.RCRC"
    },
    "MUNGARRA_GT3": {
        "facilitycode": "MUNGARRA_GT3",
        "nettmw": "WA.MGA.GEN.GT3.NTMW",
        "dispatchtarget": "WA.MGA.DISP.GT3.RBPM",
        "ramprate": "WA.MGA.DISP.GT3.RDRR",
        "description": "Mungarra Power Station GT3",
        "RLM1": "WA.MGA.DISP.GT3.RLM1",
        "RLM2": "WA.MGA.DISP.GT3.RLM2",
        "RLM3": "WA.MGA.DISP.GT3.RLM3",
        "Reg L": "WA.MGA.DISP.GT3.RLDC",
        "Reg R": "WA.MGA.DISP.GT3.RLUC",
        "Cont L": "WA.MGA.DISP.GT3.RCLC",
        "Cont R": "WA.MGA.DISP.GT3.RCRC"
    },
    "NAMKKN_MERR_SG1": {
        "facilitycode": "NAMKKN_MERR_SG1",
        "nettmw": "WA.MDP.GEN.MDP.NTMW",
        "dispatchtarget": "WA.MDP.DISP.MDP.RBPM",
        "ramprate": "WA.MDP.DISP.MDP.RDRR",
        "description": "Merredin Solar Farm SG1",
        "RLM1": "WA.MDP.DISP.MDP.RLM1",
        "RLM2": "WA.MDP.DISP.MDP.RLM2",
        #"RLM3": "WA.MDP.DISP.MDP.RLM3",
        "Reg L": "WA.MDP.DISP.MDP.RLDC",
        "Reg R": "WA.MDP.DISP.MDP.RLUC",
        "Cont L": "WA.MDP.DISP.MDP.RCLC",
        "Cont R": "WA.MDP.DISP.MDP.RCRC"
    },
    "NEWGEN_KWINANA_CCG1": {
        "facilitycode": "NEWGEN_KWINANA_CCG1",
        "nettmw": "WA.NGK.GEN.NGK.NTMW",
        "dispatchtarget": "WA.NGK.DISP.NGK.RBPM",
        "ramprate": "WA.NGK.DISP.NGK.RDRR",
        "description": "NewGen Kwinana CCG1",
        "RLM1": "WA.NGK.DISP.NGK.RLM1",
        "RLM2": "WA.NGK.DISP.NGK.RLM2",
       # "RLM3": "WA.NGK.DISP.NGK.RLM3",
        "Reg L": "WA.NGK.DISP.NGK.RLDC",
        "Reg R": "WA.NGK.DISP.NGK.RLUC",
        "Cont L": "WA.NGK.DISP.NGK.RCLC",
        "Cont R": "WA.NGK.DISP.NGK.RCRC"
    },
    "NEWGEN_NEERABUP_GT1": {
        "facilitycode": "NEWGEN_NEERABUP_GT1",
        "nettmw": "WA.GNN.GEN.GNN.NTMW",
        "dispatchtarget": "WA.GNN.DISP.GNN.RBPM",
        "ramprate": "WA.GNN.DISP.GNN.RDRR",
        "description": "NewGen Neerabup GT1",
       # "RLM1": "WA.GNN.DISP.GNN.RLM1",
        "RLM2": "WA.GNN.DISP.GNN.RLM2",
        "RLM3": "WA.GNN.DISP.GNN.RLM3",
        "Reg L": "WA.GNN.DISP.GNN.RLDC",
        "Reg R": "WA.GNN.DISP.GNN.RLUC",
        "Cont L": "WA.GNN.DISP.GNN.RCLC",
        "Cont R": "WA.GNN.DISP.GNN.RCRC"
    },
    "PERTHENERGY_KWINANA_GT1": {
        "facilitycode": "PERTHENERGY_KWINANA_GT1",
        "nettmw": "WA.KND.GEN.KND.NTMW",
        "dispatchtarget": "WA.KND.DISP.KND.RBPM",
        "ramprate": "WA.KND.DISP.KND.RDRR",
        "description": "Perth Energy Kwinana GT1",
        "RLM1": "WA.KND.DISP.KND.RLM1",
        "RLM2": "WA.KND.DISP.KND.RLM2",
        #"RLM3": "WA.KND.DISP.KND.RLM3",
        "Reg L": "WA.KND.DISP.KND.RLDC",
        "Reg R": "WA.KND.DISP.KND.RLUC",
        "Cont L": "WA.KND.DISP.KND.RCLC",
        "Cont R": "WA.KND.DISP.KND.RCRC"
    },
    "PINJAR_GT1": {
        "facilitycode": "PINJAR_GT1",
        "nettmw": "WA.PJR.GEN.GT1.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT1.RBPM",
        "ramprate": "WA.PJR.DISP.GT1.RDRR",
        "description": "Pinjar Power Station GT1",
        "RLM1": "WA.PJR.DISP.GT1.RLM1",
        "RLM2": "WA.PJR.DISP.GT1.RLM2",
        "RLM3": "WA.PJR.DISP.GT1.RLM3",
        "Reg L": "WA.PJR.DISP.GT1.RLDC",
        "Reg R": "WA.PJR.DISP.GT1.RLUC",
        "Cont L": "WA.PJR.DISP.GT1.RCLC",
        "Cont R": "WA.PJR.DISP.GT1.RCRC"
    },
    "PINJAR_GT10": {
        "facilitycode": "PINJAR_GT10",
        "nettmw": "WA.PJR.GEN.GT10.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT10.RBPM",
        "ramprate": "WA.PJR.DISP.GT10.RDRR",
        "description": "Pinjar Power Station GT10",
        "RLM1": "WA.PJR.DISP.GT10.RLM1",
        "RLM2": "WA.PJR.DISP.GT10.RLM2",
        "RLM3": "WA.PJR.DISP.GT10.RLM3",
        "Reg L": "WA.PJR.DISP.GT10.RLDC",
        "Reg R": "WA.PJR.DISP.GT10.RLUC",
        "Cont L": "WA.PJR.DISP.GT10.RCLC",
        "Cont R": "WA.PJR.DISP.GT10.RCRC"
    },
    "PINJAR_GT11": {
        "facilitycode": "PINJAR_GT11",
        "nettmw": "WA.PJR.GEN.GT11.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT11.RBPM",
        "ramprate": "WA.PJR.DISP.GT11.RDRR",
        "description": "Pinjar Power Station GT11",
        "RLM1": "WA.PJR.DISP.GT11.RLM1",
        "RLM2": "WA.PJR.DISP.GT11.RLM2",
        "RLM3": "WA.PJR.DISP.GT11.RLM3",
        "Reg L": "WA.PJR.DISP.GT11.RLDC",
        "Reg R": "WA.PJR.DISP.GT11.RLUC",
        "Cont L": "WA.PJR.DISP.GT11.RCLC",
        "Cont R": "WA.PJR.DISP.GT11.RCRC"
    },
    "PINJAR_GT2": {
        "facilitycode": "PINJAR_GT2",
        "nettmw": "WA.PJR.GEN.GT2.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT2.RBPM",
        "ramprate": "WA.PJR.DISP.GT2.RDRR",
        "description": "Pinjar Power Station GT2",
        "RLM1": "WA.PJR.DISP.GT2.RLM1",
        "RLM2": "WA.PJR.DISP.GT2.RLM2",
        "RLM3": "WA.PJR.DISP.GT2.RLM3",
        "Reg L": "WA.PJR.DISP.GT2.RLDC",
        "Reg R": "WA.PJR.DISP.GT2.RLUC",
        "Cont L": "WA.PJR.DISP.GT2.RCLC",
        "Cont R": "WA.PJR.DISP.GT2.RCRC"
    },
    "PINJAR_GT3": {
        "facilitycode": "PINJAR_GT3",
        "nettmw": "WA.PJR.GEN.GT3.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT3.RBPM",
        "ramprate": "WA.PJR.DISP.GT3.RDRR",
        "description": "Pinjar Power Station GT3",
        "RLM1": "WA.PJR.DISP.GT3.RLM1",
        "RLM2": "WA.PJR.DISP.GT3.RLM2",
        "RLM3": "WA.PJR.DISP.GT3.RLM3",
        "Reg L": "WA.PJR.DISP.GT3.RLDC",
        "Reg R": "WA.PJR.DISP.GT3.RLUC",
        "Cont L": "WA.PJR.DISP.GT3.RCLC",
        "Cont R": "WA.PJR.DISP.GT3.RCRC"
    },
    "PINJAR_GT4": {
        "facilitycode": "PINJAR_GT4",
        "nettmw": "WA.PJR.GEN.GT4.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT4.RBPM",
        "ramprate": "WA.PJR.DISP.GT4.RDRR",
        "description": "Pinjar Power Station GT4",
        "RLM1": "WA.PJR.DISP.GT4.RLM1",
        "RLM2": "WA.PJR.DISP.GT4.RLM2",
        "RLM3": "WA.PJR.DISP.GT4.RLM3",
        "Reg L": "WA.PJR.DISP.GT4.RLDC",
        "Reg R": "WA.PJR.DISP.GT4.RLUC",
        "Cont L": "WA.PJR.DISP.GT4.RCLC",
        "Cont R": "WA.PJR.DISP.GT4.RCRC"
    },
    "PINJAR_GT5": {
        "facilitycode": "PINJAR_GT5",
        "nettmw": "WA.PJR.GEN.GT5.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT5.RBPM",
        "ramprate": "WA.PJR.DISP.GT5.RDRR",
        "description": "Pinjar Power Station GT5",
        "RLM1": "WA.PJR.DISP.GT5.RLM1",
        "RLM2": "WA.PJR.DISP.GT5.RLM2",
        "RLM3": "WA.PJR.DISP.GT5.RLM3",
        "Reg L": "WA.PJR.DISP.GT5.RLDC",
        "Reg R": "WA.PJR.DISP.GT5.RLUC",
        "Cont L": "WA.PJR.DISP.GT5.RCLC",
        "Cont R": "WA.PJR.DISP.GT5.RCRC"
    },
    "PINJAR_GT7": {
        "facilitycode": "PINJAR_GT7",
        "nettmw": "WA.PJR.GEN.GT7.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT7.RBPM",
        "ramprate": "WA.PJR.DISP.GT7.RDRR",
        "description": "Pinjar Power Station GT7",
        "RLM1": "WA.PJR.DISP.GT7.RLM1",
        "RLM2": "WA.PJR.DISP.GT7.RLM2",
        "RLM3": "WA.PJR.DISP.GT7.RLM3",
        "Reg L": "WA.PJR.DISP.GT7.RLDC",
        "Reg R": "WA.PJR.DISP.GT7.RLUC",
        "Cont L": "WA.PJR.DISP.GT7.RCLC",
        "Cont R": "WA.PJR.DISP.GT7.RCRC"
    },
    "PINJAR_GT9": {
        "facilitycode": "PINJAR_GT9",
        "nettmw": "WA.PJR.GEN.GT9.NTMW",
        "dispatchtarget": "WA.PJR.DISP.GT9.RBPM",
        "ramprate": "WA.PJR.DISP.GT9.RDRR",
        "description": "Pinjar Power Station GT9",
        "RLM1": "WA.PJR.DISP.GT9.RLM1",
        "RLM2": "WA.PJR.DISP.GT9.RLM2",
        "RLM3": "WA.PJR.DISP.GT9.RLM3",
        "Reg L": "WA.PJR.DISP.GT9.RLDC",
        "Reg R": "WA.PJR.DISP.GT9.RLUC",
        "Cont L": "WA.PJR.DISP.GT9.RCLC",
        "Cont R": "WA.PJR.DISP.GT9.RCRC"
    },
    "PRK_AG": {
        "facilitycode": "PRK_AG",
        "nettmw": "WA.PKS.GEN.PKS.NTMW",
        "dispatchtarget": "WA.PKS.DISP.PKS.RBPM",
        "ramprate": "WA.PKS.DISP.PKS.RDRR",
        "description": "Parkeston Power station GT",
        #"RLM1": "WA.PKS.DISP.PKS.RLM1",
        "RLM2": "WA.PKS.DISP.PKS.RLM2",
        "RLM3": "WA.PKS.DISP.PKS.RLM3",
        "Reg L": "WA.PKS.DISP.PKS.RLDC",
        "Reg R": "WA.PKS.DISP.PKS.RLUC",
        "Cont L": "WA.PKS.DISP.PKS.RCLC",
        "Cont R": "WA.PKS.DISP.PKS.RCRC"
        },
    "ROCKINGHAM": {
        "facilitycode": "ROCKINGHAM",
        "nettmw": "WA.RO.DGEN.ROCK.NTMW",
        "dispatchtarget": "WA.RO.DISP.ROCK.RBPM",
        "ramprate": "WA.RO.DISP.ROCK.RDRR",
        "description": "Rockingham GT",
        "RLM1": "WA.RO.DISP.ROCK.RLM1",
        "RLM2": "WA.RO.DISP.ROCK.RLM2",
        "RLM3": "WA.RO.DISP.ROCK.RLM3",
        "Reg L": "WA.RO.DISP.ROCK.RLDC",
        "Reg R": "WA.RO.DISP.ROCK.RLUC",
        #"Cont L": "WA.RO.DISP.ROCK.RCLC",
        #"Cont R": "WA.RO.DISP.ROCK.RCRC"
    },
    "STHRNCRS_EG": {
        "facilitycode": "STHRNCRS_EG",
        "nettmw": "WA.WMS.GEN.SCE.NTMW",
        "dispatchtarget": "WA.WMS.DISP.SCE.RBPM",
        "ramprate": "WA.WMS.DISP.SCE.RDRR",
        "description": "Southern Cross Energy GT",
        #"RLM1": "WA.WMS.DISP.SCE.RLM1",
        "RLM2": "WA.WMS.DISP.SCE.RLM2",
        "RLM3": "WA.WMS.DISP.SCE.RLM3",
        "Reg L": "WA.WMS.DISP.SCE.RLDC",
        "Reg R": "WA.WMS.DISP.SCE.RLUC",
        "Cont L": "WA.WMS.DISP.SCE.RCLC",
        "Cont R": "WA.WMS.DISP.SCE.RCRC"
    },
    "TESLA_GERALDTON_G1": {
        "facilitycode": "TESLA_GERALDTON_G1",
        "nettmw": "WA.GTN.DGEN.TESG.NTMW",
        "dispatchtarget": "WA.GTN.DISP.TESG.RBPM",
        "ramprate": "WA.GTN.DISP.TESG.RDRR",
        "description": "Tesla Geraldton GT1",
        "RLM1": "WA.GTN.DISP.TESG.RLM1",
        "RLM2": "WA.GTN.DISP.TESG.RLM2",
        "RLM3": "WA.GTN.DISP.TESG.RLM3",
        "Reg L": "WA.GTN.DISP.TESG.RLDC",
        "Reg R": "WA.GTN.DISP.TESG.RLUC",
        "Cont L": "WA.GTN.DISP.TESG.RCLC",
        "Cont R": "WA.GTN.DISP.TESG.RCRC"
    },
    "TESLA_KEMERTON_G1": {
        "facilitycode": "TESLA_KEMERTON_G1",
        "nettmw": "WA.MRR.DGEN.TESK.NTMW",
        "dispatchtarget": "WA.MRR.DISP.TESK.RBPM",
        "ramprate": "WA.MRR.DISP.TESK.RDRR",
        "description": "Tesla Kemerton GT1",
        "RLM1": "WA.MRR.DISP.TESK.RLM1",
        "RLM2": "WA.MRR.DISP.TESK.RLM2",
        "RLM3": "WA.MRR.DISP.TESK.RLM3",
        "Reg L": "WA.MRR.DISP.TESK.RLDC",
        "Reg R": "WA.MRR.DISP.TESK.RLUC",
        "Cont L": "WA.MRR.DISP.TESK.RCLC",
        "Cont R": "WA.MRR.DISP.TESK.RCRC"
    },
    "TESLA_NORTHAM_G1": {
        "facilitycode": "TESLA_NORTHAM_G1",
        "nettmw": "WA.NOR.DGEN.TESN.NTMW",
        "dispatchtarget": "WA.NOR.DISP.TESN.RBPM",
        "ramprate": "WA.NOR.DISP.TESN.RDRR",
        "description": "Tesla Northam GT1",
        "RLM1": "WA.NOR.DISP.TESN.RLM1",
        "RLM2": "WA.NOR.DISP.TESN.RLM2",
        "RLM3": "WA.NOR.DISP.TESN.RLM3",
        "Reg L": "WA.NOR.DISP.TESN.RLDC",
        "Reg R": "WA.NOR.DISP.TESN.RLUC",
        "Cont L": "WA.NOR.DISP.TESN.RCLC",
        "Cont R": "WA.NOR.DISP.TESN.RCRC"
    },
    "TESLA_PICTON_G1": {
        "facilitycode": "TESLA_PICTON_G1",
        "nettmw": "WA.PIC.DGEN.TESP.NTMW",
        "dispatchtarget": "WA.PIC.DISP.TESP.RBPM",
        "ramprate": "WA.PIC.DISP.TESP.RDRR",
        "description": "Tesla Picton GT1",
        "RLM1": "WA.PIC.DISP.TESP.RLM1",
        "RLM2": "WA.PIC.DISP.TESP.RLM2",
        "RLM3": "WA.PIC.DISP.TESP.RLM3",
        "Reg L": "WA.PIC.DISP.TESP.RLDC",
        "Reg R": "WA.PIC.DISP.TESP.RLUC",
        "Cont L": "WA.PIC.DISP.TESP.RCLC",
        "Cont R": "WA.PIC.DISP.TESP.RCRC"
    },
    "TIWEST_COG1": {
        "facilitycode": "TIWEST_COG1",
        "nettmw": "WA.KMK.GEN.GT1.NTMW",
        "dispatchtarget": "WA.KMK.DISP.GT1.RBPM",
        "ramprate": "WA.KMK.DISP.GT1.RDRR",
        "description": "Tiwest Co-generation GT1",
       # "RLM1": "WA.KMK.DISP.GT1.RLM1",
        "RLM2": "WA.KMK.DISP.GT1.RLM2",
        "RLM3": "WA.KMK.DISP.GT1.RLM3",
        "Reg L": "WA.KMK.DISP.GT1.RLDC",
        "Reg R": "WA.KMK.DISP.GT1.RLUC",
        "Cont L": "WA.KMK.DISP.GT1.RCLC",
        "Cont R": "WA.KMK.DISP.GT1.RCRC"
    },
    "WARRADARGE_WF1": {
        "facilitycode": "WARRADARGE_WF1",
        "nettmw": "WA.WDW.GEN.WDW.NTMW",
        "dispatchtarget": "WA.WDW.DISP.WDW.RBPM",
        "ramprate": "WA.WDW.DISP.WDW.RDRR",
        "description": "Warradarge Wind Farm",
        "RLM1": "WA.WDW.DISP.WDW.RLM1",
        "RLM2": "WA.WDW.DISP.WDW.RLM2",
        "RLM3": "WA.WDW.DISP.WDW.RLM3",
        "Reg L": "WA.WDW.DISP.WDW.RLDC",
        "Reg R": "WA.WDW.DISP.WDW.RLUC",
        "Cont L": "WA.WDW.DISP.WDW.RCLC",
        "Cont R": "WA.WDW.DISP.WDW.RCRC"
    },
    "YANDIN_WF1": {
        "facilitycode": "YANDIN_WF1",
        "nettmw": "WA.YDW.GEN.YDW.NTMW",
        "dispatchtarget": "WA.YDW.DISP.YDW.RBPM",
        "ramprate": "WA.YDW.DISP.YDW.RDRR",
        "description": "Yandin Wind Farm",
        "RLM1": "WA.YDW.DISP.YDW.RLM1",
        "RLM2": "WA.YDW.DISP.YDW.RLM2",
        "RLM3": "WA.YDW.DISP.YDW.RLM3",
        "Reg L": "WA.YDW.DISP.YDW.RLDC",
        "Reg R": "WA.YDW.DISP.YDW.RLUC",
        "Cont L": "WA.YDW.DISP.YDW.RCLC",
        "Cont R": "WA.YDW.DISP.YDW.RCRC"
    },    
    "DCWL_DENMARK_WF1": {
        "facilitycode": "DCWL_DENMARK_WF1",
        "nettmw": "WA.ALB.DGEN.DCW.NTMW",
        "dispatchtarget": "WA.ALB.DISP.DCW.RBPM",
        "ramprate": "WA.ALB.DISP.DCW.RDRR",
        "description": "DCWL Denmark Wind Farm 1",
        "RLM1": "WA.ALB.DISP.DCW.RLM1",
        "RLM2": "WA.ALB.DISP.DCW.RLM2",
        "RLM3": "WA.ALB.DISP.DCW.RLM3",
        "Reg L": "WA.ALB.DISP.DCW.RLDC",
        "Reg R": "WA.ALB.DISP.DCW.RLUC",
        #"Cont L": "WA.ALB.DISP.DCW.RCLC",
        #"Cont R": "WA.ALB.DISP.DCW.RCRC"
    },
    "BLAIRFOX_WESTHILLS_WF3": {
        "facilitycode": "BLAIRFOX_WESTHILLS_WF3",
        "nettmw": "WA.RGN.DGEN.RGN3.NTMW",
        "dispatchtarget": "WA.RGN.DISP.RGN3.RBPM",
        "ramprate": "WA.RGN.DISP.RGN3.RDRR",
        "description": "Blairfox Westhills Wind Farm 3",
        "RLM1": "WA.RGN.DISP.RGN3.RLM1",
        "RLM2": "WA.RGN.DISP.RGN3.RLM2",
        "RLM3": "WA.RGN.DISP.RGN3.RLM3",
        "Reg L": "WA.RGN.DISP.RGN3.RLDC",
        "Reg R": "WA.RGN.DISP.RGN3.RLUC",
        #"Cont L": "WA.RGN.DISP.RGN3.RCLC",
        #"Cont R": "WA.RGN.DISP.RGN3.RCRC"
    },
    "SYNERGY_DSP_04": {
        "facilitycode": "SYNERGY_DSP_04",
        #"nettmw": "WA.SYN.GEN.DSP4.NTMW",
        #"dispatchtarget": "WA.SYN.DISP.DSP4.RBPM",
        #"ramprate": "WA.SYN.DISP.DSP4.RDRR",
        "description": "Synergy DSP 04",
       #"RLM1": "WA.SYN.DISP.DSP4.RLM1",
        #"RLM2": "WA.SYN.DISP.DSP4.RLM2",
        #"RLM3": "WA.SYN.DISP.DSP4.RLM3",
        #"Reg L": "WA.SYN.DISP.DSP4.RLDC",
       # "Reg R": "WA.SYN.DISP.DSP4.RLUC",
        #"Cont L": "WA.SYN.DISP.DSP4.RCLC",
        #"Cont R": "WA.SYN.DISP.DSP4.RCRC"
    },
    "HENDERSON_RENEWABLE_IG1": {
        "facilitycode": "HENDERSON_RENEWABLE_IG1",
        "nettmw": "WA.CC.DGEN.HRE.NTMW",
        "dispatchtarget": "WA.CC.DISP.HRE.RBPM",
        "ramprate": "WA.CC.DISP.HRE.RDRR",
        "description": "Henderson Renewable IG1",
        "RLM1": "WA.CC.DISP.HRE.RLM1",
        "RLM2": "WA.CC.DISP.HRE.RLM2",
        "RLM3": "WA.CC.DISP.HRE.RLM3",
        "Reg L": "WA.CC.DISP.HRE.RLDC",
        "Reg R": "WA.CC.DISP.HRE.RLUC",
        #"Cont L": "WA.CC.DISP.HRE.RCLC",
        #"Cont R": "WA.CC.DISP.HRE.RCRC"
    },
    "PREMPWR_DSP_02": {
        "facilitycode": "PREMPWR_DSP_02",
       # "nettmw": "WA.PRE.GEN.DSP2.NTMW",
        #"dispatchtarget": "WA.PRE.DISP.DSP2.RBPM",
        #"ramprate": "WA.PRE.DISP.DSP2.RDRR",
       "description": "Prempwr DSP 02",
       # "RLM1": "WA.PRE.DISP.DSP2.RLM1",
       # "RLM2": "WA.PRE.DISP.DSP2.RLM2",
       # "RLM3": "WA.PRE.DISP.DSP2.RLM3",
       # "Reg L": "WA.PRE.DISP.DSP2.RLDC",
       # "Reg R": "WA.PRE.DISP.DSP2.RLUC",
      #  "Cont L": "WA.PRE.DISP.DSP2.RCLC",
      #  "Cont R": "WA.PRE.DISP.DSP2.RCRC"
    },
    "RED_HILL": {
        "facilitycode": "RED_HILL",
        "nettmw": "WA.MJ.DGEN.RED.NTMW",
        "dispatchtarget": "WA.MJ.DISP.RED.RBPM",
        "ramprate": "WA.MJ.DISP.RED.RDRR",
        "description": "Red Hill",
        "RLM1": "WA.MJ.DISP.RED.RLM1",
        "RLM2": "WA.MJ.DISP.RED.RLM2",
        "RLM3": "WA.MJ.DISP.RED.RLM3",
        "Reg L": "WA.MJ.DISP.RED.RLDC",
        "Reg R": "WA.MJ.DISP.RED.RLUC",
        #"Cont L": "WA.MJ.DISP.RED.RCLC",
        #"Cont R": "WA.MJ.DISP.RED.RCRC"
    },
    "BLAIRFOX_BEROSRD_WF1": {
        "facilitycode": "BLAIRFOX_BEROSRD_WF1",
        "nettmw": "WA.ENB.DGEN.ZBR.NTMW",
        "dispatchtarget": "WA.ENB.DISP.ZBR.RBPM",
        "ramprate": "WA.ENB.DISP.ZBR.RDRR",
        "description": "Blairfox Berosrd Wind Farm 1",
        "RLM1": "WA.ENB.DISP.ZBR.RLM1",
        "RLM2": "WA.ENB.DISP.ZBR.RLM2",
        "RLM3": "WA.ENB.DISP.ZBR.RLM3",
        "Reg L": "WA.ENB.DISP.ZBR.RLDC",
        "Reg R": "WA.ENB.DISP.ZBR.RLUC",
        #"Cont L": "WA.ENB.DISP.ZBR.RCLC",
       # "Cont R": "WA.ENB.DISP.ZBR.RCRC"
    },
    "SOUTH_CARDUP": {
        "facilitycode": "SOUTH_CARDUP",
        "nettmw": "WA.BYF.DGEN.SCP.NTMW",
        "dispatchtarget": "WA.BYF.DISP.SCP.RBPM",
        "ramprate": "WA.BYF.DISP.SCP.RDRR",
        "description": "South Cardup",
        "RLM1": "WA.BYF.DISP.SCP.RLM1",
        "RLM2": "WA.BYF.DISP.SCP.RLM2",
        "RLM3": "WA.BYF.DISP.SCP.RLM3",
        "Reg L": "WA.BYF.DISP.SCP.RLDC",
        "Reg R": "WA.BYF.DISP.SCP.RLUC",
        #"Cont L": "WA.BYF.DISP.SCP.RCLC",
       # "Cont R": "WA.BYF.DISP.SCP.RCRC"
    },
    "BREMER_BAY_WF1": {
        "facilitycode": "BREMER_BAY_WF1",
        "nettmw": "WA.BRE.GEN.BRE.NTMW",
        "dispatchtarget": "WA.BRE.DISP.BRE.RBPM",
        "ramprate": "WA.BRE.DISP.BRE.RDRR",
        "description": "Bremer Bay Wind Farm 1",
        "RLM1": "WA.BRE.DISP.BRE.RLM1",
        "RLM2": "WA.BRE.DISP.BRE.RLM2",
        "RLM3": "WA.BRE.DISP.BRE.RLM3",
        "Reg L": "WA.BRE.DISP.BRE.RLDC",
        "Reg R": "WA.BRE.DISP.BRE.RLUC",
        #"Cont L": "WA.BRE.DISP.BRE.RCLC",
        #"Cont R": "WA.BRE.DISP.BRE.RCRC"
    },
    "TAMALA_PARK": {
        "facilitycode": "TAMALA_PARK",
        "nettmw": "WA.CKN.DGEN.TAM.NTMW",
        "dispatchtarget": "WA.CKN.DISP.TAM.RBPM",
        "ramprate": "WA.CKN.DISP.TAM.RDRR",
        "description": "Tamala Park",
        "RLM1": "WA.CKN.DISP.TAM.RLM1",
        "RLM2": "WA.CKN.DISP.TAM.RLM2",
        "RLM3": "WA.CKN.DISP.TAM.RLM3",
        "Reg L": "WA.CKN.DISP.TAM.RLDC",
        "Reg R": "WA.CKN.DISP.TAM.RLUC",
        #"Cont L": "WA.CKN.DISP.TAM.RCLC",
        #"Cont R": "WA.CKN.DISP.TAM.RCRC"
    },
    "NORTHAM_SF_PV1": {
        "facilitycode": "NORTHAM_SF_PV1",
        "nettmw": "WA.NOR.DGEN.ZNS.NTMW",
        "dispatchtarget": "WA.NOR.DISP.ZNS.RBPM",
        "ramprate": "WA.NOR.DISP.ZNS.RDRR",
        "description": "Northam Solar Farm PV1",
        "RLM1": "WA.NOR.DISP.ZNS.RLM1",
        "RLM2": "WA.NOR.DISP.ZNS.RLM2",
        "RLM3": "WA.NOR.DISP.ZNS.RLM3",
        "Reg L": "WA.NOR.DISP.ZNS.RLDC",
        "Reg R": "WA.NOR.DISP.ZNS.RLUC",
       # "Cont L": "WA.NOR.DISP.ZNS.RCLC",
       # "Cont R": "WA.NOR.DISP.ZNS.RCRC"
    },
    "KALBARRI_WF1": {
        "facilitycode": "KALBARRI_WF1",
        "nettmw": "WA.GTN.DGEN.KALWF1.NTMW",
        #"dispatchtarget": "WA.KAL.DISP.WF1.RBPM",
        #"ramprate": "WA.KAL.DISP.WF1.RDRR",
        "description": "Kalbarri Wind Farm 1",
        #"RLM1": "WA.KAL.DISP.WF1.RLM1",
        #"RLM2": "WA.KAL.DISP.WF1.RLM2",
        #"RLM3": "WA.KAL.DISP.WF1.RLM3",
       # "Reg L": "WA.KAL.DISP.WF1.RLDC",
       # "Reg R": "WA.KAL.DISP.WF1.RLUC",
       # "Cont L": "WA.KAL.DISP.WF1.RCLC",
      #  "Cont R": "WA.KAL.DISP.WF1.RCRC"
    },
    "WEST_KALGOORLIE_GT3": {
        "facilitycode": "WEST_KALGOORLIE_GT3",
        "nettmw": "WA.WKT.GEN.GT3.MW",
        "dispatchtarget": "WA.WKT.DISP.GT3.RBPM",
        "ramprate": "WA.WKT.DISP.GT3.RDRR",
        "description": "West Kalgoorlie GT3",
        "RLM1": "WA.WKT.DISP.GT3.RLM1",
        "RLM2": "WA.WKT.DISP.GT3.RLM2",
        "RLM3": "WA.WKT.DISP.GT3.RLM3",
        "Reg L": "WA.WKT.DISP.GT3.RLDC",
        "Reg R": "WA.WKT.DISP.GT3.RLUC",
        "Cont L": "WA.WKT.DISP.GT3.RCLC",
        "Cont R": "WA.WKT.DISP.GT3.RCRC"
    },
    "MWF_MUMBIDA_WF1": {
        "facilitycode": "MWF_MUMBIDA_WF1",
        "nettmw": "WA.MBW.GEN.MBW.NTMW",
        "dispatchtarget": "WA.MBW.DISP.MBW.RBPM",
        "ramprate": "WA.MBW.DISP.MBW.RDRR",
        "description": "Mumbida Wind Farm 1",
        "RLM1": "WA.MBW.DISP.MBW.RLM1",
        "RLM2": "WA.MBW.DISP.MBW.RLM2",
        "RLM3": "WA.MBW.DISP.MBW.RLM3",
        "Reg L": "WA.MBW.DISP.MBW.RLDC",
        "Reg R": "WA.MBW.DISP.MBW.RLUC",
        "Cont L": "WA.MBW.DISP.MBW.RCLC",
        "Cont R": "WA.MBW.DISP.MBW.RCRC"
    },
    "GRIFFINP_DSP_01": {
        "facilitycode": "GRIFFINP_DSP_01",
        "nettmw": "WA.GRI.GEN.DSP1.NTMW",
        #"dispatchtarget": "WA.GRI.DISP.DSP1.RBPM",
       # "ramprate": "WA.GRI.DISP.DSP1.RDRR",
        "description": "Griffin DSP 01",
       # "RLM1": "WA.GRI.DISP.DSP1.RLM1",
       # "RLM2": "WA.GRI.DISP.DSP1.RLM2",
       # "RLM3": "WA.GRI.DISP.DSP1.RLM3",
        #"Reg L": "WA.GRI.DISP.DSP1.RLDC",
       # "Reg R": "WA.GRI.DISP.DSP1.RLUC",
       # "Cont L": "WA.GRI.DISP.DSP1.RCLC",
       # "Cont R": "WA.GRI.DISP.DSP1.RCRC"
    },
    "WEST_KALGOORLIE_GT2": {
        "facilitycode": "WEST_KALGOORLIE_GT2",
        "nettmw": "WA.WKT.GEN.GT2.MW",
        "dispatchtarget": "WA.WKT.DISP.GT2.RBPM",
        "ramprate": "WA.WKT.DISP.GT2.RDRR",
        "description": "West Kalgoorlie GT2",
        "RLM1": "WA.WKT.DISP.GT2.RLM1",
        "RLM2": "WA.WKT.DISP.GT2.RLM2",
        "RLM3": "WA.WKT.DISP.GT2.RLM3",
        "Reg L": "WA.WKT.DISP.GT2.RLDC",
        "Reg R": "WA.WKT.DISP.GT2.RLUC",
        "Cont L": "WA.WKT.DISP.GT2.RCLC",
        "Cont R": "WA.WKT.DISP.GT2.RCRC"
    },
    "SKYFRM_MTBARKER_WF1": {
        "facilitycode": "SKYFRM_MTBARKER_WF1",
        "nettmw": "WA.MBR.DGEN.SKY.NTMW",
        "dispatchtarget": "WA.MBR.DISP.SKY.RBPM",
        "ramprate": "WA.MBR.DISP.SKY.RDRR",
        "description": "Skyfrm Mt Barker Wind Farm 1",
        "RLM1": "WA.MBR.DISP.SKY.RLM1",
        "RLM2": "WA.MBR.DISP.SKY.RLM2",
        "RLM3": "WA.MBR.DISP.SKY.RLM3",
        "Reg L": "WA.MBR.DISP.SKY.RLDC",
        "Reg R": "WA.MBR.DISP.SKY.RLUC",
        #"Cont L": "WA.MBR.DISP.SKY.RCLC",
        #"Cont R": "WA.MBR.DISP.SKY.RCRC"
    },
    "AMBRISOLAR_PV1": {
        "facilitycode": "AMBRISOLAR_PV1",
        "nettmw": "WA.MER.DGEN.ZMER.NTMW",
        "dispatchtarget": "WA.MER.DISP.ZMER.RBPM",
        "ramprate": "WA.MER.DISP.ZMER.RDRR",
        "description": "Ambrisolar PV1",
        "RLM1": "WA.MER.DISP.ZMER.RLM1",
        "RLM2": "WA.MER.DISP.ZMER.RLM2",
        "RLM3": "WA.MER.DISP.ZMER.RLM3",
        "Reg L": "WA.MER.DISP.ZMER.RLDC",
        "Reg R": "WA.MER.DISP.ZMER.RLUC",
        #"Cont L": "WA.MER.DISP.ZMER.RCLC",
        #"Cont R": "WA.MER.DISP.ZMER.RCRC"
    },
    "BLAIRFOX_KARAKIN_WF1": {
        "facilitycode": "BLAIRFOX_KARAKIN_WF1",
        "nettmw": "WA.RGN.DGEN.RGN1.NTMW",
        "dispatchtarget": "WA.RGN.DISP.RGN1.RBPM",
        "ramprate": "WA.RGN.DISP.RGN1.RDRR",
        "description": "Blairfox Karakin Wind Farm 1",
        "RLM1": "WA.RGN.DISP.RGN1.RLM1",
        "RLM2": "WA.RGN.DISP.RGN1.RLM2",
        "RLM3": "WA.RGN.DISP.RGN1.RLM3",
        "Reg L": "WA.RGN.DISP.RGN1.RLDC",
        "Reg R": "WA.RGN.DISP.RGN1.RLUC",
        #"Cont L": "WA.RGN.DISP.RGN1.RCLC",
       # "Cont R": "WA.RGN.DISP.RGN1.RCRC"
    },
    "BIOGAS01": {
        "facilitycode": "BIOGAS01",
        "nettmw": "WA.SNR.DGEN.BG01.NTMW",
        "dispatchtarget": "WA.SNR.DISP.BG01.RBPM",
        "ramprate": "WA.SNR.DISP.BG01.RDRR",
        "description": "Biogas 01",
        "RLM1": "WA.SNR.DISP.BG01.RLM1",
        "RLM2": "WA.SNR.DISP.BG01.RLM2",
        "RLM3": "WA.SNR.DISP.BG01.RLM3",
        "Reg L": "WA.SNR.DISP.BG01.RLDC",
        "Reg R": "WA.SNR.DISP.BG01.RLUC",
       # "Cont L": "WA.SNR.DISP.BG01.RCLC",
       # "Cont R": "WA.SNR.DISP.BG01.RCRC"
    }
}

