# Fixed tolerance values for each facility
tolerance_values = {
    "MUJA_G6": 10, "MUJA_G7": 11, "MUJA_G8": 11, "PINJAR_GT1": 6, "PINJAR_GT2": 6,
    "PINJAR_GT3": 6, "PINJAR_GT4": 6, "PINJAR_GT5": 6, "PINJAR_GT7": 6, "PINJAR_GT9": 6,
    "PINJAR_GT10": 6, "PINJAR_GT11": 6, "MUNGARRA_GT1": 6, "MUNGARRA_GT3": 6,
    "WEST_KALGOORLIE_GT2": 6, "WEST_KALGOORLIE_GT3": 6, "COCKBURN_CCG1": 12,
    "KEMERTON_GT11": 8, "KEMERTON_GT12": 8, "COLLIE_G1": 16, "STHRNCRS_EG": 6,
    "ALINTA_PNJ_U1": 7, "EDWFMAN_WF1": 6, "ALINTA_WWF": 6, "PRK_AG": 6,
    "NEWGEN_KWINANA_CCG1": 16, "ALCOA_WGP": 6, "ALINTA_PNJ_U2": 7,
    "ALINTA_WGP_GT": 11, "ALINTA_WGP_U2": 11, "BW1_BLUEWATERS_G2": 8,
    "BW2_BLUEWATERS_G1": 8, "KALAMUNDA_SG": 6, "NEWGEN_NEERABUP_GT1": 17,
    "PERTHENERGY_KWINANA_GT1": 6, "INVESTEC_COLLGAR_WF1": 6, "FLATROCKS_WF1": 6,"KWINANA_GT2": 6,
    "KWINANA_GT3": 6, "TIWEST_COG1": 6, "NAMKKN_MERR_SG1": 6, "TESLA_GERALDTON_G1": 6,
    "TESLA_KEMERTON_G1": 6, "TESLA_NORTHAM_G1": 6, "TESLA_PICTON_G1": 6,
    "MWF_MUMBIDA_WF1": 6, "BADGINGARRA_WF1": 6, "ALBANY_WF1": 6, "GRASMERE_WF1": 6,
    "GREENOUGH_RIVER_PV1": 6, "WARRADARGE_WF1": 6, "YANDIN_WF1": 6, "MERSOLAR_PV1": 6
}